name: deploy-client

on:
  push:
    branches:
      - "master"
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t jinyongnan/client .
      - run: docker login -u $MY_DOCKER_USERNAME -p $MY_DOCKER_PASSWORD
        env:
          MY_DOCKER_USERNAME: ${{ secrets.MY_DOCKER_USERNAME }}
          MY_DOCKER_PASSWORD: ${{ secrets.MY_DOCKER_PASSWORD }}
      - run: docker push jinyongnan/client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.MY_DO_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment client-depl
